### ISSUE TITLE
How to map `LengthOfTime_Min` to DwC?

### ISSUE THREAD

**Issue by damianooldoni** [riparias/pov-fishes-occurrences#1]
The fishes data can be mapped using a an occurrence core schema with occurrences linked to a measurementOrFact extension.

However, also the time needed to fishing and assess the species (and perform all other measurements I assume) is recorded. This can be interpreted as an event related information which could be mapped as `sampleSizeValue`-`sampleSizeValueUnit` from class `Event`. See https://dwc.tdwg.org/terms/#dwc:sampleSizeValue. I have so two questions:
1. can we use an event related field in an occurrence core in a DwC-A? 
2. if yes, will these two DwC terms be maintained on the long term or will be marked as outdated soon?

A second option is to add the duration in record-level field `dynamicProperties` in JSON format, see https://dwc.tdwg.org/terms/#dwc:dynamicProperties.

A third option would be to add the duration as one of the `measurementType` values.

I thought solution 1 was the best one, but if we have to add an event core just for one field seems to me quite overshooting. So, I am now voting for option 2.

@LienReyserhove and I would like to have your opinion about it. Thanks.

**Comment by peterdesmet** [comment]
Yes, `sampleSizeValue` and `sampleSizeUnit` can be added to an occurrence core. That's also your only option, since you want to link occurrences to measurements, and the star schema doesn't allow to have event + occurrences + measurements.

1. For meetnetten and other datasets, we typically express that information in `samplingEffort` ([example](https://github.com/inbo/meetnetten-occurrences/blob/154ef1097be288d4993612262f553290bfe05f0b/datasets/26%20meetnetten-abv-occurrences/specs/dwc_event.yaml#L38-L39)), but sampleSizeValue and SampleSizeUnit fit better.

3. I would avoid using `dynamicProperties` if you can.
4. An additional `measurementType` is also an option, maybe even in combination with 1

**Comment by damianooldoni** [comment]
Interpretation of this field asked to Filip Mahieu. At the moment I map it as `sampleSizeValue`/`sampleSizeUnit` in event core.

**Comment by damianooldoni** [comment]
Answer of @filipmahieu:
> LengthOfTime_Min: dit is het aantal minuten dat bvb de fuik in het water heeft gelegen en zo ‘vissen heeft verzameld’.

**Comment by peterdesmet** [comment]
Seems like a good one for `samplingEffort`

**Comment by peterdesmet** [comment]
Both in MOF is good
